### PR TITLE
Visual Studio 2022 support with .NET 6 installation

### PR DESCRIPTION
**Pull request by StanDeMan**
*  Support for Visual Studio 2022 only because of Visual Studio  SDK API changes
*  .NET 6 gets installed the first time starting the debugger with a Raspian without .NET installed 
   -> no tests done if any .NET is preinstalled. Behaviour for this situation is unkown so far. 
* Using standard OpenSSH from Windows 10/11
*  Only actual .NET SDKs versions (Core 3.1. .NET 5 + 6) included in catalog json

### CODE REVIEW

**Comment by MagicAndre1981** [comment]
can you also add my PR #38 and provide a vsix until this is merged ?

**Comment by SidineiSantosSousa** [comment]
Can you provide the vsix file? Thank you for the hard work!

**Comment by StanDeMan** [comment]
> 



> Can you provide the vsix file? Thank you for the hard work!

For me it was a pleasure. The hard work was done by nforgeio. I am fairly new to github. Where can I make the vsix file available? Let me know, please.

**Comment by MagicAndre1981** [comment]
> Where can I make the vsix file available? Let me know, please.

submit it with an [different ID to gallery](https://www.vsixgallery.com/devguide) until it is merged.

Can you also add my PR and update the lib to 17.x version.

**Comment by SidineiSantosSousa** [comment]
If you build the project the .vsix file will be generated.
[Debug.zip](https://github.com/nforgeio/RaspberryDebugger/files/8072578/Debug.zip)

**Comment by StanDeMan** [comment]
Thanks MagicAndre1981, I'll try to submit it to gallery.

**Comment by tlemmons** [comment]
I checked out this branch and built it then used the debug vsix to install to VS 2022.  However when I go to add a new raspberry connection and fill in the known good details, it locks up and I have to kill VS with the task manager.  Any ideas before I start digging into a debug cycle?

**Comment by tlemmons** [comment]
Thanks Stan,  This if for my second job so it may be weekend before I can dig but I will do.

**Comment by daim2k5** [comment]
@StanDeMan do you need still help to publish the vsix?
@jefflill sounds good. Are you suggest @StanDeMan as Maintainer?

**Comment by StanDeMan** [comment]
@daim2k5 Nop. Thanks. Kann publish the VSIX.

Without fixing the mentioned (known) issues:
- ASP.NET -> Debugger wants to have an "Absolute Path" -> this is something to ask Microsoft to get it fixed. Pretty strange! ;)
- Only one project in a solution gets deployed to RasPi

I try to publish till end of this week.
@all Feel free to get the known issues from above fixed, please.
@jefflill Thanks a lot for your great work!
Kindest Regards
Stanislaus

**Comment by StanDeMan** [comment]
@all I published the vsix but it is private in the market place. Does Mircosoft check it first - like Google does in their stores?

**Comment by daim2k5** [comment]
@StanDeMan which status do you see on https://marketplace.visualstudio.com/manage ?

**Comment by StanDeMan** [comment]
@daim2k5 hm? Still "not public". Maybe I need to get a publisher, registering a DNS - what i don't have? I'll watch the youtube video. Thanks a lot.

**Comment by StanDeMan** [comment]
@all Now it's public. Missed the free dots and the menu in there - making it public. ;)
@daim2k5 Thanks for the video.
ASP.NET is still an issue - telling the debugger a "Absolue Path" is needed. So feel free to fix this if someone is able, please. If not I'll open an issus at MS VS team to get this (ASP.NET 6?) bug closed.

**Comment by MagicAndre1981** [comment]
> @ALL Now it's public. Missed the free dots and the menu in there - making it public. ;) https://marketplace.visualstudio.com/items?itemName=GingerMintSoft-OpenSource.RaspberryDebugger
> 

thanks, works so far in 17.2 Preview 1.0 with console app with .net 6 and RP4 . 

rasppi_debug

But if a csproj contains more at least 2 targetframeworks, the app always runs on the local windows with. So it would be nice to port my PR to VS2022

**Comment by StanDeMan** [comment]
@ [MagicAndre1981] Thanks a lot for your feedback. Can you do the PR against my repo, please? I'll do the port asap. 
@ all ASP.NET debugging is still not working because of ASP.NET 6 wants to have an "absolute path". This is so strange! :(
If someone is able to fix this send the PR too please.

**Comment by MagicAndre1981** [comment]
> @ [MagicAndre1981] Thanks a lot for your feedback. Can you do the PR against my repo, please? I'll do the port asap. 

Ok, I created a PR, but I can't test my PR, because the entry `Raspberry Debug Settings` is missing in the 2022 version and I have no idea to debug this.

**Comment by StanDeMan** [comment]
@ MagicAndre1981 Thanks for the PR. Let me see. For the moment I only support .NET 6 - as mentioned for upload. So I have to do more work here...
Debugging is really simple. Open the VSIX project and start it as usual with F5 -> the VSIX gets startet inside a Visual Studio Instance. Now you have two instances running - one hosting the VSIX and the Studio with the opened VSIX Code for debugging. With a powerfull computer debugging should go smooth.

**Comment by MagicAndre1981** [comment]
yes, this is clear, but I have no idea where to find the code that shows the entry Raspberry Debug Settings and why it doesn't show up.

**Comment by MagicAndre1981** [comment]
ok, [IsActiveProjectRaspberryCompatible](https://github.com/nforgeio/RaspberryDebugger/blob/c1b902e2b1320b32eb3a52f4fba1c8631eba7776/RaspberryDebugger/Commands/SettingsCommand.cs#L90) returns false for csproj with multiple TargetFrameworks in your version and true for original extension in VS2019. This is why the entry is removed from menu.

**Comment by StanDeMan** [comment]
@MagicAndre1981 Thanks a lot. I'll take the PR and check this. If everything goes well I'll create and push a new VSiX.
Thanks again.

**Comment by MagicAndre1981** [comment]
ok, the check for [IsStandalone looks to be the cause for returning false](https://github.com/nforgeio/RaspberryDebugger/blob/c1b902e2b1320b32eb3a52f4fba1c8631eba7776/RaspberryDebugger/Models/VisualStudio/ProjectProperties.cs#L134). Adding `PackageHelper.SdkGoodCatalog.Items` to watch window shows only .net 6 has IsStandalone set to true. But where does this come from?

**Comment by MagicAndre1981** [comment]
ok, this IsStandalone is indeed wrong. The [100, 200, 300 are feature levels](https://docs.microsoft.com/en-us/dotnet/core/versions/#versioning-details) and no indication for standalone or VS bundled SDK version. 100 is the first SDK shipped with VS2022 17.0, 200 is shipped/compatible with VS2022 17.1. if you don't use Visual Studio at all, always pick the highest version to get most features. 

rasppi_debug_

I need to test it more, but my original PR still works, I have csproj with 3 frameworks and my selected 6.0 can be debugged.

You also need to update the SDK/runtimes to lastest versions from March 2022 patchday.

**Comment by MagicAndre1981** [comment]
there are more bugs. The `TargetFrameworkMonikers` from project system in[ CopyFrom method](https://github.com/nforgeio/RaspberryDebugger/blob/f5f3c710c21ed7df363bd944e28c9f9077d9b42c/RaspberryDebugger/Models/VisualStudio/ProjectProperties.cs#L110) only returns the first targetframework, so `<TargetFrameworks>netcoreapp3.1;net48</TargetFrameworks>` would treat the project as compatible.

**Comment by Reveon** [comment]
@StanDeMan 

I am using Blazor Wasm and I was also getting 'The path must be absolute' Exception if there is no 
 `<RuntimeIdentifier>linux-arm</RuntimeIdentifier>` in sever csproj but with it it works just fine. 

Adding my Server and Client csproj config - maybe it helps.

server csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PublishTrimmed>false</PublishTrimmed>
    <RuntimeIdentifier>linux-arm</RuntimeIdentifier>
  </PropertyGroup>
```

Blazor csproj:
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly" TreatAsLocalProperty="SelfContained">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <PublishTrimmed>true</PublishTrimmed>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
```

**Comment by StanDeMan** [comment]
> @StanDeMan
> 
> I am using Blazor Wasm and I was also getting 'The path must be absolute' Exception if there is no `<RuntimeIdentifier>linux-arm</RuntimeIdentifier>` in sever csproj but with it it works just fine.
> 
> Adding my Server and Client csproj config - maybe it helps.
> 
> server csproj:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Web">
>   <PropertyGroup>
>     <TargetFramework>net6.0</TargetFramework>
>     <PublishTrimmed>false</PublishTrimmed>
>     <RuntimeIdentifier>linux-arm</RuntimeIdentifier>
>   </PropertyGroup>
> ```
> 
> Blazor csproj:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly" TreatAsLocalProperty="SelfContained">
>   <PropertyGroup>
>     <TargetFramework>net6.0</TargetFramework>
>     <Nullable>enable</Nullable>
>     <ImplicitUsings>enable</ImplicitUsings>
>     <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
>     <PublishTrimmed>true</PublishTrimmed>
>     <SelfContained>true</SelfContained>
>   </PropertyGroup>
> ```

@Reveon 

Thanks a lot for this hint. I get exactly the same error if I try to debug ASP.NET projects with wwwroot path - without wwwroot everything is working well. Hopefully I'll have a few free minutes this weekend to take MagicAndre1981's changes and test this hint. It would be nice if a new version can be built and made available in NuGet. I'll see what can be done. Thanks a lot for the support.

**Comment by tlemmons** [comment]
Sorry I have been away and swamped.  Just getting back to this.  I have downloaded the latest built and trying to debug.  When I create a new connection to my raspberry pi 4, it tries to connect and never returns.  I have traced it to connection.cs -> connectAsync line 91.  I have tried changing the timespan to a few seconds and putting a try catch around it but it still never returns.  Any ideas on tracing farther in or why this would be the case?  @StanDeMan you said it needed an "Absolute path" but I am not seeing anything about that.

**Comment by tlemmons** [comment]
I have downloaded the neon projects and started tracing through.  Looks like the LinuxSSHProxy system is trying to verify a file exists ("/etc/neon-sshproxy-init") andlocking up on an upload of a cmd.sh file.  @jefflill this is your original code.  Do you know what might be happening here or why it is causing a hang?

**Comment by jefflill** [comment]
My first guess is that sudo on the Pi is prompting for a password.  LinuxSshProxy tries to add the user to the sudoers and then creates the `/etc/neon-sshproxy-init` file after that's done so the class won't need to do that again.  One thing to try would be to manually make the user a sudoer and see what happens.

I'm sorry I haven't had much time to work on this debugger.  Raspberry Pi was a hobby thing that I ended up not having time to actually play with much yet.

Would you and Stan like to become maintainers for this thing?  I could probably grant you rights to publish to the VS Marketplace as well (I assume that's possible).

My main project (neonKUBE) is finally coming to a head so I'll probably have a bit more time to have a life and help out with this.  And I also have some ideas for perhaps forking the Raspberry Debugger myself for use with Kubernetes scenarios.

**Comment by tlemmons** [comment]
I just checked.  In a normal ssh (putty) session, I can call "sudo ls" and no password is requested.

**Comment by tlemmons** [comment]
As much as I would love to help out, I am afraid that I would not have time for maintaining a project like this.  I am able to jump in and fix something often when I need it for my day, night, or weekend job(s).  Too many things already.

**Comment by tlemmons** [comment]
I think I got that fixed.  It was actually my path for non-interactive shell did not include /bin or path to mkdir so with no folders nothing else was working.

**Comment by StanDeMan** [comment]
> <RuntimeIdentifier>linux-arm</RuntimeIdentifier>



> <RuntimeIdentifier>linux-arm</RuntimeIdentifier>

@Reveon 
That's it! Had to place <RuntimeIdentifier>linux-arm</RuntimeIdentifier> into Propertygroup in my project file.
I nearly got nuts about this issue. Nothing to do with the debugger. Thanks a lot! Cheers!

**Comment by jefflill** [comment]
Sorry, I'm cleaning out my old mail.

Yeah, I could add @StanDeMan <https://github.com/StanDeMan>as a maintainer
if he likes and also give him rights to the publish the VSIX to the Visual
Studio MarketPlace.

**Comment by StanDeMan** [comment]
> 

Hi Jeff, it's okay for me to give me the rights. You are welcome. I published the stuff on my own VS Marketplace. 
Let me know if this is okay for you? 

I implemented a html grepping service to grep the actual .NET versions every day into a json file, too. Do you know where I can host this for free? My Azure Account gets shut off for some days at the end of the month - having too many services hosted. ;) Heroku seems not to be an option. Wasn't able to host for free so far. Don't know why this wasn't working? Have to try once again. If the service cannot be reached the debugger is still working - using the deployed json in the debugger release - only actual on release date. But the service is always sending the actual .NET versions available on Microsoft download pages.

Thanks a lot for your great work and tool! We love it! :)

Kindest regards
StanDeMan

**Comment by jefflill** [comment]
Merged to: **main**

**Pull request merged**
